blank_issues_enabled: true
contact_links:
  - name: PrismLauncher Matrix Support Room
    url: https://matrix.to/#/#prismlauncher:matrix.org
    about: Please ask for support here before opening an issue.
