name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: PrismLauncher.PrismLauncher
          version: ${{ github.event.release.tag_name }}
          installers-regex: 'PrismLauncher-Windows-MSVC(-arm64|-Legacy-Setup)?-\d.+\.(exe|msix)?$'
          token: ${{ secrets.WINGET_TOKEN }}
